name: Bushcraft Dad
favicon: null
layout_spectrum: 0.9985013615805656
typography_spectrum: 0.6265680203214288
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3434399387333542
  lightness: 0.6631603061687201
  saturation: 0.7803928011562675
  rhythmicContrast: 0.07319343811832368
purpose: []
